spring:
  datasource:
    url: jdbc:mysql://localhost/xss
    username: xhcms
    password: 123456
  security:
    user:
      name: "madao"
      password: "1234"

server:
  port: 8433

mybatis:
  mapper-locations: classpath:generator/*.xml

